version : '3'
services:
  rabbitmq:
    image: 'rabbitmq:management-alpine'
    hostname: rabbitmq
    ports:
      - '5672:5672' 
      - '8080:15672'
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmquser
      RABBITMQ_DEFAULT_PASS: pa55word